version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build:
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: |
          psql \
          -d $TEST_DATABASE_URL
      - run:
          command: |
            python -m venv trav_env
            source trav_env/bin/activate
            pip install -r requirements.txt
          name: Install Dependencies
      - run:
          command: |
            source trav_env/bin/activate
            coverage run -m pytest
            coverage report -m
            coveralls
          name: Run test with coverage



