version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build:
    docker:
      - image: cimg/python:3.10
      - image: cimg/postgres:14.0
        environment:
          TESTING_POSTGRES_USER: postgres
          TESTING_POSTGRES_PW: password123
          TESTING_POSTGRES_HOST: localhost
          TESTING_DB_NAME: postgres
    steps:
      - checkout
      - run:
          command: |
            python -m venv trav_env
            source trav_env/bin/activate
            pip install -r requirements.txt
          name: Install Dependencies
      - run:
          command: |
            source trav_env/bin/activate
            coverage run -m pytest
            coverage report -m
            coveralls
          name: Run test with coverage



