version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build:
    docker:
      - image: circleci/python:3.9
        environment:
          TEST_DATABASE_URL: postgresql://imisi@localhost/postgres
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Wait for db to run
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          command: |
            python -m venv trav_env
            source trav_env/bin/activate
            pip install -r requirements.txt
          name: Install Dependencies
      - run:
          command: |
            source trav_env/bin/activate
            coverage run -m pytest
            coverage report -m
            coveralls
          name: Run test with coverage



