category_tuple=[('Business',),
    ('Adventure',),
    ('Wildlife',),
    ('Medical',),
    ('Wellness',),
    ('Pilgrimage and Spiritual',),
    ('Cultural',),
    ('Dark',),
    ('Culinary',),
    ('Celibrity',),
    ('Educational',),
    ('Cruise',),
    ('Rural',),
    ('Beach',),
    ('Space',),
    ('Lake',),
    ('Park',),
]