INSERT INTO places (name, location, country, about) VALUES 
              ('Shark Bay', 'Gascoyne', 'Australia', 'The most westerly point on mainland Australia is this UNESCO World Heritage Site. It was founded in the 17th Century'),
              ('Paracas', 'Paracas', 'Peru', 'A small seaside town in the Ica region of Peru, Paracas is where the desert meets the sea'),
              ('Algarve', 'Portugal', 'Portugal', 'It is known for its surfing, picturesque cities, local crafts, cuisine, golden sand beaches and natural marvels.'),
              ('Paris', 'Paris', 'France', 'It is known worldwide for the Louvre Museum, Notre-Dame cathedral, and the Eiffel tower.'),
              ('Sarakiniko beach', 'Greece', 'Greece', 'A beach on Milos Island, Greece, situated on the north shore of the island.'),
              ('Antarctic Peninsula', 'Antarctica', 'Antarctica', 'It stretches toward South America. It’s known for the Lemaire Channel and Paradise Harbor, striking, iceberg-flanked passageways, and Port Lockroy'),
              ('Death Valley', 'California', 'United States of America', 'Hottest place on earth'),
              ('Provence', 'France', 'France', 'It is famous for its sunny weather, colorful countryside, tradition, wine, food, and language '),
              ('Bayon', 'Angkor', 'Cambodia', 'The Bayon is a richly decorated Khmer temple related to Buddhism at Angkor in Cambodia.'),
              ('Grand Teton National Park', 'Wyoming', 'Wyoming', 'Located only 10 miles from Yellowstone National Park, Grand Teton National Park is a stunning national park in Wyoming.'),
              ('Angel Falls', 'Canaima National Park', 'Venezuela', 'The world’s highest waterfall, with 3,212ft cascades, is located in the UNESCO-protected Canaima National Park and was the inspiration for the Disney film Up. The site is only accessible by boat or plane.'),
              ('Kyrgyzstan', 'Kyrgyzstan', 'Kyrgyzstan', 'It has natural beauty. Unspoilt pine forests, rocky ridges and rolling jailoos (summer pastures) are typical of the country.'),
              ('Grand Canal', 'Venice','Italy', 'it’s the grandest waterway in the Floating City'),
              ('Hwange National park', 'Hwange', 'Zimbabwe', 'Hwange has a greater diversity of mammals than any national park in the world and is the largest natural reserve in Zimbabwe.'),
              ('Mongolia', 'Mongolia', 'Mongolia', '18th-largest country in the world, Visitors can go local: riding horses, helping to look after livestock and sleeping in a herder’s ger'),
              ('Lake Eyre', 'Australia', 'Australia', 'It dries due to evaporated water, with its salt-deposit haze, the body only fills completely twice every 100 years on average.'),
              ('Bali', 'Indonesia', 'Indonesia', 'One of Indonesia’s 17,000 islands and sees an average temperature of about 30°C year round. Explore by bicycle and then head to one of its many cool beach clubs.'),
              ('Seven Sisters Country park', 'East Sussex', 'United Kingdom', 'Made up of 280 hectares of chalk cliffs, a winding river valley and flat top grasslands with views of the English Channel'),
              ('Atacama desert', 'Chile', 'Chile', 'The driest nonpolar desert in the world, as well as the only true desert to receive less precipitation than the polar deserts and the largest fog desert in the world.'),
              ('Mount Fuji', 'Honshu', 'Japan', 'A sacred mountain and symbol'),
              ('Jaipur and the Hawa Mahal palace', 'Rajasthan', 'India', 'It is filled to the brim with buzzing bazaars, sacred lakes and gilded royal palaces'),
              ('Skeleton coast', 'Namibia', 'Namibia', 'They are endless miles of stone and sand, dry riverbeds and dunes Desert-adapted animals here include elephant, giraffe, lion, brown hyaena and Cape fur seals that thrive in the area'),
              ('The Scotish highlands', 'Scotland', 'United Kingdom', 'There’s natural beauty everywhere, from babbling Fairy Pools and big-horned cattle to clear coastal waters and snowy mountain caps'),
              ('Pamukale', 'Pamukkale', 'Turkey', 'It is made up of layers of white travertine terraces of ice-blue spa pools.'),
              ('The ALPS', 'Austria', 'Austria', 'The most extensive mountain range in Europe. It Stretch over eight countries, France, Switzerland, Monaco, Italy, Liechtenstein, Austria, Germany and Slovenia.'),
              ('Bazaruto Archipelago', 'Vilankulo', 'Mozambique', 'A protected marine park, its waters are rich in manta rays, schools of dolphins, hawksbill turtles and dugongs'),
              ('Ojos Del Mar', 'Bolivia', 'Bolivia', 'The water can change slightly in colour, depending on the angle of the sun, from bright blue to seafoam green.'),
              ('Mount Cook', 'Canterbury', 'New Zealand', 'More than 40 per cent of the area is covered in glaciers, with the largest and longest named the Tasman Glacier'),
              ('Emerald Lake', 'British Columbia', 'Canada', 'Backed by the towering mountain peaks of the President Range, in summer the clear glacial water is ideal for canoeing and attempting a quick swim.'),
              ('Hong Kong', 'Hong Kong', 'Hong Kong', 'Modern high-rise buildings meet period architecture in retro'),
              ('Antelope Canyon', 'Arizona', 'United States of America', 'The place where water runs through rocks’ and the narrow ravine'),
              ('Svalbard', 'Norway', 'Norway', 'It has one of the harshest environments on the planet. Nearly two-thirds of it is protected and the islands are made up of bird sanctuaries, nature reserves and national parks where polar bears roam'),
              ('Copenhagen', 'Copenhagen', 'Denmark', 'The forward-thinking capital of Scandi cool appeals to foodies, design junkies and a cool young crowd'),
              ('Lamu', 'Lamu Island', 'Kenya', 'Lamu has hosted major Muslim religious festivals since the 19th century, and has become a significant centre for the study of Islamic and Swahili cultures'),
              ('Wulingyuan', 'Wulingyuan', 'China', 'It is known for exotic peaks, its unusually shaped stones, its deep and secluded ravines, its waters, and its limestone caves.'),
              ('Redwood National Park', 'San Francisco', 'United States of America', 'It has more than more than 200 miles of trail routes, it’s ideal for camping, hiking and riding.'),
              ('Havana', 'Havana', 'Cuba', 'Havana is known for its old architecture, vintage cars, beautiful beaches, and tasty Cuban cocktails,'),
              ('Kyoto', 'Kyoto', 'Japan', 'It is awash with ancient temples and shrines, serene teahouses and sublime gardens'),
              ('Ischia', 'Italy', 'Italy', 'It is a volcanic island in the Tyrrhenian Sea. It lies at the northern end of the Gulf of Naples, about 30 kilometres (19 miles) from Naples'),
              ('Jerusalem', 'Jerusalem', 'Israel', 'The Old City, sacred to a number of religions, blends grand design with places of prayer.'),
              ('Bondi Icebergs', 'Sydney', 'Australia', 'The Olympic-size structure has been standing on the southern end of Bondi Beach for more than 100 years.'),
              ('Las Coloradas', 'Yucatan', 'Mexico', 'The incredible pink lakes here make up part of the protected nature reserve of Ría Lagartos Biosphere on Mexico’s Yucatán peninsula'),
              ('Shakespeare’s Birthplace', 'Stratford', 'United Kingdom', 'Here, he spent most of his life penning his sonnets'),
              ('Globe Theatre', 'London', 'United Kingdom', 'It remains a shining beacon of English artistic heritage and presents reenactments of many of Shakespeare’s dramas today.'),
              ('Trojan Horse', 'Troy', 'Turkey', 'The artefact that turned the tide of the Trojan War birthed the first two European literature works;'),
              ('Ephesus', 'Ephesus', 'Turkey', 'The stature of monuments such as the Library of Celsus and the Great Theatre is genuinely breathtaking.'),
              ('Fairy Chimneys', 'Cappadocia', 'Turkey', 'This geological marvel is a cave town; dotted with humble abodes above and underground.'),
              ('The Colosseum', 'Rome', 'Italy', 'The largest amphitheatre ever built during the Roman Empire'),
              ('The Sistine Chapel', 'The Vatican Palace', 'Italy', 'The most famous being The Sistine Chapel ceiling depicting the “Creation of Adam” curated by Michelangelo in the 16th century.'),
              ('Pompeii', 'Campania', 'Italy', 'For any curious soul wanting to have a taste of the lifestyle back then, Pompeii allows you to traverse through the town hall and old thermal baths'),
              ('Olympia Stadium', 'Peloponnese peninsula', 'Greece', 'This is the birthplace of the ancient Olympic Games, which was a festival celebrating Zeus'),
              ('Theatre of Dionysus', 'Athens', 'Greece', 'Lauded as the world’s first theatre and the birthplace of Greek Tragedy'),
              ('San Diego Natural History Museum', 'San Diego', 'United States of America', 'Fascinating museum is an attractive destination for field trips for its exemplary exhibits and interactive components'),
              ('USS Midway Museum', 'San Diego', 'United States of America', 'For groups emphasizing American history in general, or even military history in particular, the USS Midway Museum is an ideal attraction.'),
              ('U.S. Space and Rocket Center', 'Alabama', 'United States of America', 'This world-renowned museum features exhibits that reveal NASA’s achievements and you’ll also find the world’s largest space attraction'),
              ('Plymouth rock and Mayflower', 'Plymouth', 'United States of America', 'They can see both of those iconic landmarks to get a real understanding of how Native Americans and the pilgrims lived'),
              ('Chernobyl', 'Chernobyl', 'Ukraine', 'The disaster was a nuclear accident that occurred on 26 April 1986 at the No. 4 reactor in the Chernobyl Nuclear Power Plant,'),
              ('Hiroshima Peace Memorial Park', 'Hiroshima', 'Japan', 'It was largely destroyed by an atomic bomb during World War II.'),
              ('Murambi Genocide Memorial', 'Murambi', 'Rwanda', '50,000 Tutsi men, women and children were massacred by the Interahamwe militia and soldiers loyal to the government responsible for the genocide.'),
              ('Hollywood', 'Los Angeles', 'United States of America', 'A larger-than-life symbol of the entertainment business'),
              ('Dominican Republic', 'Carribean', 'Dominican Republic', 'The Dominican Republic is a Caribbean nation that shares the island of Hispaniola with Haiti to the west. It’s known for its beaches, resorts and golfing'),
              ('The Maldives', 'Indian Ocean', 'Maldives', 'It is an archipelagic country located in Southern Asia, situated in the Indian Ocean'),
              ('Turks and Caicos', 'Grand Turk', 'United Kingdom', 'Endless white sand beaches and turquoise waters'),
              ('St. Barts', 'Saint Barthelemy', 'France', 'It is home to an array of stunning beaches, luxury yachts, designer boutiques, and breathtaking restaurants that have helped it become a travel hotspot.'),
              ('Aspen', 'Colorado', 'United States of America', 'It is a ski resort town and year-round destination for outdoor recreation.'),
              ('Spa Grande ', 'Hawaii', 'United States of America', 'It is the largest health resort in Hawaii, with 50,000 square feet dedicated to relevant activities.'),
              ('Adler Thermae Spa Resort', 'Italy', 'Italy', 'The resort includes hiking and cycling trails that cover just short of 125 miles of Tuscan landscape and offers guided hikes to wine tastings'),
              ('Costa Rica', 'Costa Rica ', 'Costa Rica ', 'it has warmwater beaches with year-round waves, or it might be the unique hot springs and volcanoes.'),
              ('Paris', 'France', 'France', 'When people plan their trips to Paris, they tend to forget that the city is a foodie paradise, even though it’s in France.'),
              ('Mendoza', 'Argentina', 'Argentina', 'A perfect spot for foodies'),
              ('Tuscany', 'Italy', 'Italy', 'Making tender, homemade pasta and rich meaty tomato sauces, drinking wine in Tuscany and eating briny olives and antipasto on the terrace overlooking the vineyards'),
              ('San Sebastian', 'Spain', 'Spain', 'Greatest food destination in the world, with more Michelin stars per capita than any other city'),
              ('Bordeaux', 'France', 'France', 'Combine the delicious wines of Bordeaux with the gorgeous scenery '),
              ('New York City', 'United States of America', 'United States of America', 'Here you’ll find incredible food everywhere'),
              ('Tokyo', 'Japan', 'Japan', 'You will find the freshest, best, most amazing sushi in the world.'),
              ('Bangkok', 'Thailand', 'Thailand', 'Thai food is very much a universally loved cuisine'),
              ('London', 'United Kingdom', 'United Kingdom', 'London is the food capital of the world.'),
              ('Melbourne', 'Australia', 'Australia', 'A great food city, with many great restaurants to check out around the city'),
              ('Stellenbosch', 'South Africa', 'South Africa', 'The winery experience is so much more inviting and relaxed here.'),
              ('Mexico City', 'Mexico', 'Mexico', 'Eat burritos, carnitas, enchiladas, tacos and guacamole all day, every day and be perfectly content.'),
              ('Lima', 'Peru', 'Peru', 'Lima’s signature dishes, like ceviche and chicharones, are becoming favorites around the world and opening people’s eyes to the flavors of Peru'),
              ('New Orleans', 'Louisiana', 'United States of America', 'Not only does New Orleans have an abundance of great chefs and dining experiences, it also boasts a rather sophisticated cocktail scene.'),
              ('Istanbul', 'Turkey', 'Turkey', 'From seaside resorts on the Mediterranean Sea, historical sites, welcoming people, rich culture, amazing museums and delicious Turkish dishes'),
              ('Catalunya', 'Spain', 'Spain', 'Catalunya is one of those regions, and the amount of unique products, recipes and foods you can find there is astounding.'),
              ('Osun Osogbo Festival', 'Osogbo', 'Nigeria', 'The festival of Osun-Osgobo, which takes place every year in Osogbo, Nigeria, celebrates the goddess of fertility, Osun'),
              ('Ecuador', 'Ecuador', 'Ecuador', 'A visit to an Indigenous community, where you’ll learn to make traditional dishes and beverages such as chicha'),
              ('Big Island of Hawaii', 'Hawaii', 'Hawaii', 'Known for Palm-weaving, stargazing and petroglyphs'),
              ('Orleans Parish', 'New Orleans', 'United States of America', 'Known for Jazz, Madi Gras and Creole cooking'), 
              ('Oaxaca', 'Mexico', 'Mexico', 'For indigenous cuisine, Zapotec rugs, and Mezcal'),
              ('Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Known for Old bazaars, woodcarving, and Kahva'),
              ('Russia', 'Russia', 'Russia', 'Known for Ballet, Banyas, and Borscht'),
              ('Andalusia', 'Spain', 'Spain', 'Marvel at the Moorish architecture, Go tapas hopping, and Watch a Flamenco performance'),
              ('Central Australia', 'Australia', 'Australia', 'Known for ancient landscapes, ochre, and bush tucker'),
              ('Timor-Leste', 'Timor-Leste', 'Timor-Leste', 'Known for sacred houses, Tais weaving and Cristo rei'),
              ('Sarawak', 'Malaysia', 'Malaysia', 'Known for Ikat textiles, long houses and Forest trekking'),
              ('Cambodia', 'Cambodia', 'Cambodia', 'Watch an Apsara performance, Go forest trekking in Mondulkiri:, and Seek out Khmer handicrafts'),
              ('Japan', 'Japan', 'Japan', 'Observe a temple ritual, Spend the night in a ryokan, and Drink matcha'),
              ('Bhutan', 'Bhutan', 'Bhutan', 'Known for handicrafts, thangka, fertility symbols'),
              ('Kerala', 'India', 'India', 'Known for houseboats, tea estates and contemporary arts'),
              ('Rajasthan', 'India', 'India', 'Known for folk dance, thaali, and Camel fairs'),
              ('Uzbekistan', 'Uzbekistan', 'Uzbekistan', 'Known for ceramics, silk road heritage and traditional dance performance'),
              ('Taipei', 'Taiwan', 'Taiwan', 'Known for night markets, Confusianism and forbidden relics'),
              ('Ethiopia', 'Ethiopia', 'Ethiopia', 'Participate in traditional coffe ceremony'),
              ('Oman', 'Oman', 'Oman', 'Known for Dhow boats, frankincense, and bedouin culture'),
              ('Tel Aviv ', 'Galilee', 'Israel', 'Visitors can see the terraced hillsides and irrigation channels that farmers built thousands of years ago'),
              ('Ein Gedi', 'Mesada', 'Israel', 'Near the Dead Sea shows visitors how Israel has transformed the desert'),
              ('Taramundi', 'Taramundi', 'Spain', 'Its village will make you fall in love, specially if you love nature'),
              ('El Rompido', 'El Rompido', 'Spain', 'If you just crave a few peaceful days enjoying the waves, one of the best rural getaways is this village'),
              ('Bavarian forest', 'Germany', 'Germany', 'It is the largest protected forest area in central Europe.'),
              ('Gudiana river', 'Portugal', 'Portugal', 'It is an international river defining a long stretch of the Portugal-Spain border, separating Extremadura and Andalusia from Alentejo and Algarve.'),
              ('Madeira', 'Portugal', 'Portugal', 'Madeira Rural is a private non-profitable organization aiming at developing and promoting rural tourism and the activities of its associates in particular'),
              ('Canary Islands', 'Spain', 'Spain', 'You can enjoy long hours of sunshine with barely any clouds all year round and mild temperatures with no major changes.'),
              ('Parque Agroecologico Merecure', 'Colombia', 'Colombia', 'The property is quite vast and has several lakes, where tourists can go swimming or kayaking. Hiking, bike rides and sport fishing are also available.'),
              ('Puerto Lopez ', 'Ecuador', 'Ecuador', 'The main industries include fishing and ecotourism. The street closest to the beach has many restaurants, cabanas that provide drinks'),
              ('Parque Agroecologico Tierra Prometida', 'Quindio', 'Colombia', 'It is truly a paradise for nature lovers and agrotourism. Besides stunning hikes, visitors can take part in tree planting and other traditional activities related to the coffee culture.'),
              ('Rif Mountains', 'Chefchaouen', 'Morocco', 'There are plenty of hiking and trekking opportunities in the mountains, which you can do with an organized tour or on your own'),
              ('Atlas Mountains', 'Imlil', 'Morocco', 'Pleasant, serene places to stay. These towns are great starting points for hikes and treks'),
              ('Berber Villages', 'Morocco', 'Morocco', 'Listen to their Berber language and learn about their way of life, as it’s an enriching insight into the ancient cultures of Morocco'),
              ('Padma Resort Ubud', 'Bali', 'Indonesia', 'Enjoy yoga, an onsite spa, beautiful pools and a gorgeous setting'),
              ('The Cacciatora Wellness and Beauty Hotel', 'Italy', 'Italy', 'Tucked into the jagged peaks of the Val di Fassa. Hiking trails on the doorstep, Tyrolean spa Check and Charming chalet feel'),
              ('Sigiriana Resort ', 'Sri Lanka', 'Sri Lanka ', 'For your spiritual health'),
              ('Himalayas', 'Rishikesh', 'India', 'They offer immersion weeks or months that involve ritualistic mantra chanting, meditation, vows of silence, and cleansing dips in the ghats'),
              ('Monterrey', 'Mexico', 'Mexico', 'Specializes in weight loss treatment and surgery'),
              ('Tijuana', 'Mexico', 'Mexico', 'Specializes in weight loss treatment and surgery'),
              ('Bangalore', 'India', 'India', 'Treatments to have in India include those for fertility, orthopedic, cardiac and oncology problems and organ transplants'),
              ('Mumbai', 'India', 'India', 'Treatments to have in India include those for fertility, orthopedic, cardiac and oncology problems and organ transplants'),
              ('Bangkok', 'Thailand', 'Thailand', 'They are known for its meticulous cosmetic surgery, including gender reassignment.'),
              ('Ivo Pitanguy Clinic', 'Rio de Janeiro', 'Brazil', 'Popular destination for cosmetic surgery'),
              ('Gleneagles Hospital ', 'Singapore', 'Singapore', 'Specializes in cardiology, gastroenterology, liver transplants and orthopaedics'),
              ('Kuala Lumpur ', 'Malaysia', 'Malaysia', 'Vision, dental, hearing and MRI and PET scans'),
              ('Johns Hopkins Hospital ', 'Baltimore', 'United States of America', 'Offers technologies and surgical expertise'),
              ('Cleveland Clinic ', 'Ohio', 'United States of America', 'Offers technologies and surgical expertise'),
              ('The Dunyagöz Hospitals Group', 'Turkey', 'Turkey', 'It has established itself as a center for eye treatment in particular, and offers inexpensive laser surgery'),
              ('Gyor ', 'Hungary', 'Hungary', 'Offers Cosmetic or restorative dental procedures'),
              ('Palomar Observatory', 'San Diego', 'United States of America', 'The Observatory houses the world’s once-largest telescope, the 5.1m Hale Telescope, operated chiefly by computers now rather than humans.'),
              ('Kennedy Space Center', 'Florida', 'United States of America', 'This is the granddaddy of all space facilities, the launch pad for the Mercury, Gemini and Apollo programmes, as well as the various space shuttles'),
              ('Baikonur Cosmodrome', 'Kazakhstan', 'Kazakhstan', 'This is the world’s oldest facility for launching space vehicles'),
              ('Arecibo Radio Telescope', 'Puerto Rico', 'Puerto Rico', ' Houses the world’s largest radio telescope, a beautiful structure (a work of art to many) featuring a huge, spherical reflector dish, 300m in diameter, composed of 40,000 perforated aluminium panels embedded into the surrounding jungle'),
              ('Very Large Array', 'New Mexico', 'United States of America', 'The VLA consists of 27 radio antennas, each 25m wide, arranged in a Yshape, with one arm of the array extending 21km'),
              ('Star City', 'Russia', 'Russia', 'You will be able to visit the awesome Space Museum, with its 20,000 exhibits including space suits, space vehicles and assorted Gagarinalia'),
              ('Jiuquan Satellite Launch Centre', 'China', 'China', 'It’s in the desert, but because of the whole space infrastructure, it’s not as primitive as other isolated Chinese towns.'),
              ('Tanegashima Space Center', 'Japan', 'Japan', 'Visit the launch complexes and interact with the wonderful full-scale simulacra of the Japanese Experiment Module.'),
              ('Spaceport America', 'New Mexico', 'United States of America', 'Flights are expected to begin in the next couple of years, so you have just enough time to save up the  $200,000 needed for a ticket'),
              ('Chicago', 'Chicago', 'United States of America', ' It’s world-class architecture, thriving arts scene and world renowned sports teams ensure that America’s “Second City” has got something for everyone.'),
              ('San Francisco', 'San Francisco', 'United States of America', 'America’s most creative and forward-thinking city'),
              ('New York', 'New York', 'United States of America', 'America’s most powerful financial institutions, media corporations and communications agencies'),
              ('Philadephia', 'Philadephia', 'United States of America', 'One of the globe’s top centers for bio-science. It’s also a national base for tourism and financial services'),
              ('Rio de Janeiro', 'Rio de Janeiro', 'Brazil', 'Premier hub for media, communications and higher education'),
              ('Phoenix', 'Arizona', 'United States of America', 'A strong technology industry, never-ending sunshine and rich art scene provide business travelers with fantastic events and a whole host of stimulating activities.'),
              ('London', 'London', 'United Kingdom', 'Offers businesses unrivaled access to some of the globe’s top multinationals'),
              ('Toronto', 'Canada', 'Canada', 'Canada’s biggest city is a center for financial services and manufacturing'),
              ('Mexico City', 'Mexico', 'Mexico', 'Global leader in consumer products and pharmaceuticals'),
              ('Salt Lake City', 'Utah', 'United States of America', 'America’s leading business destinations for technology, computing and outdoor retail'),
              ('Dublin', 'Ireland', 'Ireland', 'Welcomes travel, tech and social media conferences'),
              ('Louisville', 'Kentucky', 'United States of America', 'It has grown to become one of America’s top healthcare hubs'),
              ('Cancun', 'Mexico', 'Mexico', 'The beach destination is rapidly evolving into one of the continent’s top destinations for business travel'),
              ('Singapore', 'Singapore', 'Singapore', 'The city-state harbors the best business growth environment on the planet, and is a major financial capital'),
              ('Las Vegas', 'Nevada', 'United States of America', 'Las Vegas hosts a wide range of graphics, communications and manufacturing events that are widely considered industry staples'),
              ('Sao Paulo', 'Brazil', 'Brazil', 'South America’s most influential financial districts'),
              ('Frankfurt', 'Frankfurt', 'Germany', 'Europe’s top aviation hub'),
              ('Brussels', 'Belgium', 'Belgium', 'Host the European Union parliament and some of the continent’s finest art collections, but it also boasts a diverse music scene'),
              ('Istanbul', 'Istanbul', 'Turkey', 'Most well established meeting points for geographically isolated corporate partners'),
              ('Portland', 'Oregon', 'United States of America', 'It’s a major hub for renewable energy companies, higher education and scientific research.'),
              ('Madrid', 'Madrid', 'Spain', 'The city boasts some of the world’s most sophisticated conference venues and convention centers.'),
              ('Denver', 'Colorado', 'United States of America', 'The city also supports a wide range of rapidly growing technology and communications companies'),
              ('West Palm Beach', 'Florida', 'United States of America', 'The city plays home to a diverse range of events that make for fantastic marketing and networking opportunities'),
              ('Paris', 'France', 'France', 'Paris has one of the globe’s highest concentrations of corporate behemoths, including oil companies and investment banks.'),
              ('Everglades National Park', 'Florida', 'United States of America', 'A home to a wide range of unique and interesting animals'),
              ('Mana Pools National Park', 'Zambezi', 'Zimbabwe', 'The park is home to four of the Big Five animals of Africa'),
              ('Rainforest', 'Atsinanana', 'Madagascar', 'Visitors to the parks will get to see animals that can be found nowhere else in the world.'),
              ('Ujung Kulon National Park', 'Kulon Peninsula', 'Indonesia', 'It is most well known for its endangered Javan rhinos, which are critically endangered.'),
              ('Lone Pine Sanctuary', 'Brisbane', 'Australia', 'The sanctuary includes koalas, kangaroos, wombats, dingos, platypus, Tasmanian devils, and the dangerous Southern cassowary bird for visitors to see.'),
              ('Jim Corbett National Park', 'India', 'India', 'The Jim Corbett National Park is probably most famous for its rich population of Bengal tigers.'),
              ('Bandhavgarh National Park', 'India', 'India', 'The park has some amazing wildlife.  This includes Bengal tigers, Indian dholes, Indian wolves, Indian leopards, sloth bears, and the unique striped hyena'),
              ('Sabi Sands Game Reserve', 'Kruger', 'South Africa', 'The Sabi Sands Game Reserve has all of the Big Five animals of Africa (elephants, buffalo, lions, leopards, and rhinoceros), as well as some of the best safari guides in the world to help you locate and view them.'),
              ('Okavango Delta', 'Botswana', 'Botswana', 'The park offers both walking safaris as well as mokoro (or dugout canoe) trips, which are great additions to supplement the wonderful game drives within the park.'),
              ('Kruger National Park', 'Kruger', 'South Africa', 'Kruger also offers a great choice of lodging for all budgets, which makes going on safari a relatively affordable adventure for any traveler.'),  
              ('Corcovado National Park', 'Puntarenas', 'Coasta Rica', 'The park is comprised of a staggering 13 different major ecosystems including lowland rain forest, cloud forest, Jolillo palm forest, and mangrove swamps.'),
              ('Yellowstone National Park', 'Wyoming', 'United States of America', 'Large numbers of grazing animals including American bison, Roosevelt elk, and Pronghorn antelope graze in the park’s large valleys.'),
              ('Katmai National Park', 'Alaska', 'United States of America', 'The park is known the world over because of the large numbers of Alaskan brown bears that are attracted to the park to fish for the masses of salmon that migrate up the park’s rivers'),
              ('Etosha National Park', 'Namibia', 'Namibia', 'Home to some of Africa’s tallest elephants, the endangered black rhino, an abundant population of cheetah, as well as healthy herds of zebra, wildebeest, and African buffalo that can be found throughout the park.'),
              ('Serengeti National Park', 'Tanzania', 'Tanzania', 'The park is home to some of the biggest herds of grazing animals in Africa, which in turn attracts some of the largest numbers of predators in sub-Saharan Africa.'),
              ('Yala National Park', 'Sri Lanka', 'Sri Lanka', 'It is home to a mind-boggling array of spectacular wildlife. This includes Sri Lankan leopards, Sri Lankan elephants, Sri Lankan sloth bears, and a variety of other mammals, reptiles, and birds.'),
              ('South Luangwa National Park', 'Zambia', 'Zambia', 'South Luangwa National Park in Zambia is truly an amazing wildlife viewing destination.  With one of the densest populations of leopards in Africa'),
              ('Gir National Park', 'India', 'India', 'Visitors have a good chance of seeing asiatic lions, Indian leopards, striped hyenas, golden jackals, and the infamous Indian cobra.'),
              ('Gunung Leuser National Park', 'Indonesia', 'Indonesia', 'This park gives a close to a real jungle experience that you can find in the region. With the endangered Sumatran rhino, the Sumatran elephant, and the Sumatran Tiger still accessible for visitors to see in the park'),
              ('Volcanoes National Park', 'Rwanda', 'Rwanda', 'As one of the last remaining refuges for the mountain gorillas of Africa, Volcanoes National Park is an absolute must-see for travelers who love wildlife'),
              ('The Amazon Basin', 'Brazil', 'Brazil', 'For wildlife enthusiasts who would like to experience this unique and amazing place, your best bet is to visit the Amazon Basin in Brazil.'),
              ('Masai Mara National Reserve', 'Narok', 'Kenya', 'Here, You are almost guaranteed to see the three big cats of Southern Africa (the African lion, the African leopard, and the African cheetah), as well as elephants, giraffe, and seemingly endless herds of buffalo, antelope, and zebra.'),
              ('Kaziranga National Park', 'Assam', 'India', 'The park has the largest number of remaining Indian rhinos, it also has an abundant supply of Bengal tigers, Indian elephants, Asiatic black bears, Indian leopards, sloth bears, and an amazing array of other wildlife.'),
              ('The Ngorongoro Crater', 'Tanzania', 'Tanzania', 'Here, you are close to assured of seeing the Big Five animals of Africa'),
              ('Vietnam', 'Vietnam', 'Vietnam', 'gives an opportunity to visit the cities and towns located along the Gulf of Thailand and the South China Sea. You can even cruise along the Mekong River and enjoy the spellbinding natural beauty and biodiversity.'),
              ('Mediterranean Sea', 'Spain', 'Spain', 'A cruise of the Western Mediterranean region will take you to Rome, Venice, and Sicily in Italy, St. Tropez, Monte Carlo, and Barcelona. You can opt for a cruise of Eastern Mediterranean that will take you to Turkey and the Greek islands of Santorini, Crete, and Mykonos or a Southern Mediterranean cruise that will enable you to visit Egypt, Tunisia, and Morocco.'),
              ('Galapagos Islands', 'Ecuador', 'Ecuador', 'you will be able to visit the island that inspired Charles Darwin to come up with his Theory of Evolution by Natural Selection. A cruise of the islands allows you to see the giant tortoises, sea lion, iguanas and a plethora of unique bird species not found anywhere else.'),
              ('Alaska', 'Alaska', 'United States of America', 'Most cruises to Alaska depart from Vancouver or Seattle and drop anchor in stunning locales, like Glacier Bay National Park, Skagway, Juneau, Tracy Arm Fjord, and the Inside Passage.'),
              ('Panama Canal', 'Panama', 'Panamas', 'You can visit the Amazon Rainforest and enjoy river cruises to feed alligators, photograph a plethora of bird species, go piranha fishing or frolic with pink dolphins.'),
              ('Mecca', 'Makkah', 'Saudi Arabia', 'Non-Muslims are not allowed inside Mecca, the holiest place in Islam, so this excursion is only for believers. Every year, millions of Muslims embark on a journey to Mecca, called the Hajj.'),
              ('Sri Pada', 'Sri Lanka', 'Sri Lanka', 'Religious destination for four major religious groups; Buddhism, Christianity, Islam, Hinduism'),
              ('Vatican City', 'Rome', 'Italy', 'Home of the Pope and centre of the Roman Catholic Church'),
              ('Wittenberg', 'Saxony', 'Germany', 'Birthplace of the Protestant Reformation'),
              ('Golden Temple', 'Amritsar', 'India', 'Holiest place of worship for Sikhs'),
              ('Western Wall', 'Jerusalem', 'Israel', 'The holiest of Jewish sites'),
              ('Lumbini', 'Rupandehi', 'Nepal', 'Birthplace of the Lord Buddha'),
              ('Lucerne', 'Switzerland', 'Switzerland', 'Here you can visit the remains of an ancient settlement dating back to the 9th century and feel the true spirit of centuries of antiquity'),
              ('Delft', 'Netherlands', 'Netherlands', 'If you wish to immerse yourself in the old atmosphere of Europe, go to Dutch Delft, considered one of the most beautiful cities in the country.');